pickle_dir: './dataset'
log_dir: '../drive/MyDrive/'
epochs: 1000
batch_size: 4
load_path:
dropout: 0.1
debug: ''
l_r: 0.001
label_smooth: 0.1
experiment: 'embedding512-layer6'
max_seq: 2048
embedding_dim: 512
num_layers: 6
event_dim: 388
fp16:
